import type { RuntimeSecretKey, RuntimeFeatureId } from './runtime-config';

export const SIGNUP_URLS: Partial<Record<RuntimeSecretKey, string>> = {
  WORLDMONITOR_API_KEY: 'https://worldmonitor.app',
  GROQ_API_KEY: 'https://console.groq.com/keys',
  OPENROUTER_API_KEY: 'https://openrouter.ai/settings/keys',
  FRED_API_KEY: 'https://fred.stlouisfed.org/docs/api/api_key.html',
  EIA_API_KEY: 'https://www.eia.gov/opendata/register.php',
  CLOUDFLARE_API_TOKEN: 'https://dash.cloudflare.com/profile/api-tokens',
  ACLED_ACCESS_TOKEN: 'https://developer.acleddata.com/',
  ACLED_EMAIL: 'https://developer.acleddata.com/',
  URLHAUS_AUTH_KEY: 'https://auth.abuse.ch/',
  OTX_API_KEY: 'https://otx.alienvault.com/',
  ABUSEIPDB_API_KEY: 'https://www.abuseipdb.com/login',
  WINGBITS_API_KEY: 'https://wingbits.com/register',
  AISSTREAM_API_KEY: 'https://aisstream.io/authenticate',
  OPENSKY_CLIENT_ID: 'https://opensky-network.org/login?view=registration',
  OPENSKY_CLIENT_SECRET: 'https://opensky-network.org/login?view=registration',
  FINNHUB_API_KEY: 'https://finnhub.io/register',
  NASA_FIRMS_API_KEY: 'https://firms.modaps.eosdis.nasa.gov/api/area/',
  UC_DP_KEY: 'https://ucdp.uu.se/downloads/',
  OLLAMA_API_URL: 'https://ollama.com/download',
  OLLAMA_MODEL: 'https://ollama.com/library',
  WTO_API_KEY: 'https://apiportal.wto.org/',
  AVIATIONSTACK_API: 'https://aviationstack.com/signup/free',
  ICAO_API_KEY: 'https://dataservices.icao.int/',
  THREATFOX_API_KEY: 'https://auth.abuse.ch/',
  NEWSAPI_KEY: 'https://newsapi.org/register',
  NEWSDATA_API_KEY: 'https://newsdata.io/register',
  VIRUSTOTAL_API_KEY: 'https://www.virustotal.com/gui/join-us',
  BGPVIEW_API_KEY: 'https://bgpview.io/',
  FMP_API_KEY: 'https://financialmodelingprep.com/developer/docs',
  SHODAN_API_KEY: 'https://account.shodan.io/',
  OWM_API_KEY: 'https://openweathermap.org/api',
  GREYNOISE_API_KEY: 'https://www.greynoise.io/plans/community',
  NASA_API_KEY: 'https://api.nasa.gov/#signUp',
  URLSCAN_API_KEY: 'https://urlscan.io/user/signup',
  BITCOINABUSE_API_KEY: 'https://www.bitcoinabuse.com/api-docs',
  VULNERS_API_KEY: 'https://vulners.com/docs/api/',
  MEDIASTACK_API_KEY: 'https://mediastack.com/signup/free',
  PULSEDIVE_API_KEY: 'https://pulsedive.com/api/',
  HIBP_API_KEY: 'https://haveibeenpwned.com/API/Key',
  GEONAMES_USERNAME: 'https://www.geonames.org/login',
  IPINFO_TOKEN: 'https://ipinfo.io/signup',
  CESIUM_ION_TOKEN: 'https://ion.cesium.com/signup/',
  GOOGLE_MAPS_API_KEY: 'https://console.cloud.google.com/apis/credentials',
  WINDY_WEBCAMS_API_KEY: 'https://api.windy.com/keys',
};

export const PLAINTEXT_KEYS = new Set<RuntimeSecretKey>([
  'OLLAMA_API_URL',
  'OLLAMA_MODEL',
  'WS_RELAY_URL',
  'VITE_OPENSKY_RELAY_URL',
  'ACLED_EMAIL',
]);

export const MASKED_SENTINEL = '__WM_MASKED__';

export const HUMAN_LABELS: Record<RuntimeSecretKey, string> = {
  WORLDMONITOR_API_KEY: 'World Monitor Cloud API Key',
  ANTHROPIC_API_KEY: 'Anthropic API Key',
  GROQ_API_KEY: 'Groq API Key',
  OPENROUTER_API_KEY: 'OpenRouter API Key',
  FRED_API_KEY: 'FRED API Key',
  EIA_API_KEY: 'EIA API Key',
  CLOUDFLARE_API_TOKEN: 'Cloudflare API Token',
  ACLED_ACCESS_TOKEN: 'ACLED Access Token',
  ACLED_EMAIL: 'ACLED Registered Email',
  ACLED_REFRESH_TOKEN: 'ACLED Refresh Token',
  URLHAUS_AUTH_KEY: 'URLhaus Auth Key',
  OTX_API_KEY: 'AlienVault OTX Key',
  ABUSEIPDB_API_KEY: 'AbuseIPDB API Key',
  WINGBITS_API_KEY: 'Wingbits API Key',
  WS_RELAY_URL: 'WebSocket Relay URL',
  VITE_OPENSKY_RELAY_URL: 'OpenSky Relay URL',
  OPENSKY_CLIENT_ID: 'OpenSky Client ID',
  OPENSKY_CLIENT_SECRET: 'OpenSky Client Secret',
  AISSTREAM_API_KEY: 'AISStream API Key',
  FINNHUB_API_KEY: 'Finnhub API Key',
  NASA_FIRMS_API_KEY: 'NASA FIRMS API Key',
  UC_DP_KEY: 'UCDP API Key',
  OLLAMA_API_URL: 'Ollama Server URL',
  OLLAMA_MODEL: 'Ollama Model',
  WTO_API_KEY: 'WTO API Key',
  AVIATIONSTACK_API: 'AviationStack API Key',
  ICAO_API_KEY: 'ICAO NOTAM API Key',
  THREATFOX_API_KEY: 'ThreatFox API Key',
  NEWSAPI_KEY: 'NewsAPI Key',
  NEWSDATA_API_KEY: 'NewsData API Key',
  VIRUSTOTAL_API_KEY: 'VirusTotal API Key',
  BGPVIEW_API_KEY: 'BGPView API Key',
  FMP_API_KEY: 'Financial Modeling Prep API Key',
  SHODAN_API_KEY: 'Shodan API Key',
  OWM_API_KEY: 'OpenWeatherMap API Key',
  GREYNOISE_API_KEY: 'GreyNoise API Key',
  NASA_API_KEY: 'NASA API Key (optional — improves DONKI rate limit)',
  URLSCAN_API_KEY: 'URLScan.io API Key',
  BITCOINABUSE_API_KEY: 'Bitcoin Abuse API Key',
  VULNERS_API_KEY: 'Vulners API Key',
  MEDIASTACK_API_KEY: 'MediaStack API Key',
  PULSEDIVE_API_KEY: 'Pulsedive API Key',
  HIBP_API_KEY: 'Have I Been Pwned API Key',
  GEONAMES_USERNAME: 'GeoNames Username',
  IPINFO_TOKEN: 'IPInfo Token',
  CESIUM_ION_TOKEN: 'Cesium Ion Token',
  GOOGLE_MAPS_API_KEY: 'Google Maps API Key',
  WINDY_WEBCAMS_API_KEY: 'Windy Webcams API Key',
};

export interface SettingsCategory {
  id: string;
  label: string;
  features: RuntimeFeatureId[];
}

export const SETTINGS_CATEGORIES: SettingsCategory[] = [
  {
    id: 'ai',
    label: 'AI & Summarization',
    features: ['aiClaude', 'aiOllama', 'aiGroq', 'aiOpenRouter'],
  },
  {
    id: 'economy',
    label: 'Economic & Energy',
    features: ['economicFred', 'energyEia', 'supplyChain', 'secEdgar'],
  },
  {
    id: 'markets',
    label: 'Markets & Trade',
    features: ['finnhubMarkets', 'fmpMarketsFallback', 'wtoTrade'],
  },
  {
    id: 'security',
    label: 'Security & Threats',
    features: ['cloudApiFallbackAuth', 'internetOutages', 'acledConflicts', 'acledAirstrikes', 'abuseChThreatIntel', 'alienvaultOtxThreatIntel', 'abuseIpdbThreatIntel', 'threatfoxThreatIntel', 'openPhishThreatIntel', 'phishstatsFeed', 'spamhausDrop', 'cisaKev', 'cveTracker', 'vulnersCve', 'virusTotalEnrichment', 'bgpViewEnrichment', 'shodanIcsExposure', 'greynoiseIntel', 'urlscanThreatIntel', 'bitcoinabuseIocs', 'pulsediveThreatIntel', 'hibpBreach', 'ripeNccData', 'openSanctions'],
  },
  {
    id: 'tracking',
    label: 'Tracking & Sensing',
    features: ['aisRelay', 'openskyRelay', 'wingbitsEnrichment', 'nasaFirms', 'aviationStack', 'icaoNotams', 'openWeatherMap', 'openAqMonitor', 'geoDbCities', 'geoNames', 'ipInfoLookup', 'windyWebcams', 'dotTrafficCams'],
  },
  {
    id: 'news',
    label: 'News & Media',
    features: ['newsApiHeadlines', 'newsDataFeed', 'mediastackNews', 'redditOsint'],
  },
  {
    id: 'conflict-analysis',
    label: 'Conflict Analysis',
    features: ['iswSituationReports', 'reliefwebCrises', 'bellingcatOsint', 'liveUaMapFeed'],
  },
  {
    id: 'military-diplomatic',
    label: 'Military & Diplomatic',
    features: ['dodNewsRss', 'natoNewsRss', 'acapsCrisisSeverity', 'emscSeismic', 'govWarningConvergence'],
  },
  {
    id: 'travel-warnings',
    label: 'Travel Warnings',
    features: ['fcdoTravelWarnings', 'dfatTravelWarnings', 'gacTravelWarnings'],
  },
];
