import type { PanelConfig, MapLayers } from '@/types';
import type { DataSourceId } from '@/services/data-freshness';
import { SITE_VARIANT } from './variant';

// ============================================
// FULL VARIANT (Geopolitical)
// ============================================
// Panel order matters. Lead with watchlists and escalation workflow before raw feeds.
const FULL_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Global Map', enabled: true, priority: 1 },
  watchlist: { name: 'Watchlist & Playbooks', enabled: true, priority: 1 },
  'saved-places': { name: 'Saved Places', enabled: true, priority: 1 },
  'watchlist-locations': { name: 'Watched Locations', enabled: true, priority: 1 },
  'local-logistics': { name: 'Local Logistics', enabled: true, priority: 1 },
  'comms-plan': { name: 'Tactical Comms', enabled: true, priority: 1 },
  'unified-alert-inbox': { name: 'Alert Inbox', enabled: true, priority: 1 },
  'alert-rules': { name: 'Alert Rules', enabled: true, priority: 1 },
  'situation-awareness': { name: 'Situation Awareness', enabled: true, priority: 1 },
  'alert-center': { name: 'Alert Center', enabled: true, priority: 1 },
  'strategic-risk': { name: 'Strategic Risk Overview', enabled: true, priority: 1 },
  'strategic-posture': { name: 'AI Strategic Posture', enabled: true, priority: 1 },
  insights: { name: 'AI Insights', enabled: true, priority: 1 },
  cii: { name: 'Country Instability', enabled: true, priority: 1 },
  'geo-hubs': { name: 'Geopolitical Hubs', enabled: true, priority: 1 },
  'live-news': { name: 'Live News', enabled: true, priority: 1 },
  'live-webcams': { name: 'Live Webcams', enabled: true, priority: 1 },
  intel: { name: 'Intel Feed', enabled: true, priority: 1 },
  'gdelt-intel': { name: 'Live Intelligence', enabled: true, priority: 1 },
  cascade: { name: 'Infrastructure Cascade', enabled: true, priority: 1 },
  politics: { name: 'World News', enabled: true, priority: 1 },
  us: { name: 'United States', enabled: true, priority: 1 },
  europe: { name: 'Europe', enabled: true, priority: 1 },
  middleeast: { name: 'Middle East', enabled: true, priority: 1 },
  africa: { name: 'Africa', enabled: true, priority: 1 },
  latam: { name: 'Latin America', enabled: true, priority: 1 },
  asia: { name: 'Asia-Pacific', enabled: true, priority: 1 },
  energy: { name: 'Energy & Resources', enabled: true, priority: 1 },
  gov: { name: 'Government', enabled: true, priority: 1 },
  thinktanks: { name: 'Think Tanks', enabled: true, priority: 1 },
  polymarket: { name: 'Predictions', enabled: true, priority: 1 },
  commodities: { name: 'Commodities', enabled: true, priority: 1 },
  markets: { name: 'Markets', enabled: true, priority: 1 },
  economic: { name: 'Economic Indicators', enabled: true, priority: 1 },
  'economic-stress': { name: 'Economic Stress', enabled: true, priority: 2 },
  'federal-register': { name: 'Federal Register', enabled: true, priority: 2 },
  'trade-policy': { name: 'Trade Policy', enabled: true, priority: 1 },
  'supply-chain': { name: 'Supply Chain', enabled: true, priority: 1 },
  finance: { name: 'Financial', enabled: true, priority: 1 },
  tech: { name: 'Technology', enabled: true, priority: 2 },
  crypto: { name: 'Crypto', enabled: true, priority: 2 },
  heatmap: { name: 'Sector Heatmap', enabled: true, priority: 2 },
  ai: { name: 'AI/ML', enabled: true, priority: 2 },
  layoffs: { name: 'Layoffs Tracker', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 2 },
  'satellite-fires': { name: 'Fires', enabled: true, priority: 2 },
  earthquakes: { name: 'Earthquakes', enabled: true, priority: 2 },
  'cyber-threats': { name: 'Cyber Threats', enabled: true, priority: 2 },
  'local-ids': { name: 'Local IDS', enabled: false, priority: 2 },
  'comms-health': { name: 'Communications Health', enabled: true, priority: 2 },
  'macro-signals': { name: 'Market Radar', enabled: true, priority: 2 },
  'etf-flows': { name: 'BTC ETF Tracker', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  'ucdp-events': { name: 'UCDP Conflict Events', enabled: true, priority: 2 },
  'nuclear-risk': { name: 'Nuclear Risk Tracker', enabled: true, priority: 2 },
  'airstrikes': { name: 'Air Strikes & Drones', enabled: true, priority: 2 },
  giving: { name: 'Global Giving', enabled: true, priority: 2 },
  'stoic-reflections': { name: 'Stoic Reflections', enabled: true, priority: 3 },
  'biblical-encouragement': { name: 'Biblical Encouragement', enabled: true, priority: 3 },
  'alan-watts-reflections': { name: 'Alan Watts', enabled: true, priority: 3 },
  'mckenna-visions': { name: 'Terence McKenna', enabled: true, priority: 3 },
  'daily-wisdom': { name: 'Daily Wisdom', enabled: true, priority: 3 },
  displacement: { name: 'UNHCR Displacement', enabled: true, priority: 2 },
  climate: { name: 'Climate Anomalies', enabled: true, priority: 2 },
  'population-exposure': { name: 'Population Exposure', enabled: true, priority: 2 },
  'security-advisories': { name: 'Security Advisories', enabled: true, priority: 2 },
  'oref-sirens': { name: 'Israel Sirens', enabled: true, priority: 2 },
  'telegram-intel': { name: 'Telegram Intel', enabled: true, priority: 2 },
  'space-weather': { name: 'Space Weather', enabled: true, priority: 2 },
  'spaceflight-news': { name: 'Spaceflight News', enabled: true, priority: 2 },
  'space-launches': { name: 'Space Launches', enabled: true, priority: 2 },
  'disease-outbreaks': { name: 'Disease Outbreaks', enabled: true, priority: 2 },
  'disease-intel': { name: 'Disease Intelligence', enabled: true, priority: 2 },
  'humanitarian-crisis': { name: 'Humanitarian Crises', enabled: true, priority: 2 },
  'air-quality': { name: 'Air Quality', enabled: true, priority: 2 },
  'wildfire-incidents': { name: 'Wildfires (InciWeb)', enabled: true, priority: 2 },
  'hazmat-incidents': { name: 'Hazmat Incidents', enabled: true, priority: 2 },
  'oil-spill': { name: 'Oil & Chemical Spills', enabled: true, priority: 2 },
  'unified-inbox': { name: 'Alert Inbox', enabled: true, priority: 1 },
  'hazard-alerts': { name: 'Hazard Alerts — Near Me', enabled: true, priority: 1 },
  'infrastructure': { name: 'Critical Infrastructure', enabled: true, priority: 2 },
  'gdacs-alerts': { name: 'GDACS Disaster Alerts', enabled: true, priority: 2 },
  'volcano-alerts': { name: 'Volcano Alerts', enabled: true, priority: 2 },
  'nws-alerts': { name: 'NWS Hazard Alerts', enabled: true, priority: 2 },
  'faa-weather-cams': { name: 'FAA Weather Cams', enabled: true, priority: 2 },
  'tsunami-alerts': { name: 'Tsunami Alerts', enabled: true, priority: 2 },
  'tropical-cyclones': { name: 'Tropical Cyclones', enabled: true, priority: 2 },
  'food-insecurity': { name: 'Food Insecurity', enabled: true, priority: 2 },
  'radiation-decay': { name: 'Radiation Decay Calculator', enabled: true, priority: 3 },
  'resource-inventory': { name: 'Resource Inventory', enabled: true, priority: 3 },
  'fear-greed': { name: 'Fear & Greed Index', enabled: true, priority: 2 },
  'internet-disruptions': { name: 'Internet Disruptions', enabled: true, priority: 2 },
  'national-debt': { name: 'National Debt', enabled: true, priority: 2 },
  'fuel-prices': { name: 'Fuel Prices', enabled: true, priority: 2 },
  'air-traffic': { name: 'Air Traffic', enabled: true, priority: 2 },
  'global-weather': { name: 'Global Weather', enabled: true, priority: 2 },
  'opensanctions': { name: 'Global Sanctions', enabled: true, priority: 2 },
  'edgar-filings': { name: 'SEC EDGAR Filings', enabled: true, priority: 2 },
  'isw-reports': { name: 'ISW Situation Reports', enabled: true, priority: 1 },
  'reliefweb-crises': { name: 'UN OCHA Crisis Reports', enabled: true, priority: 1 },
  'bellingcat-osint': { name: 'Bellingcat OSINT', enabled: true, priority: 2 },
  'emsc-seismic': { name: 'Nuclear Test Watch', enabled: true, priority: 1 },
  'fcdo-warnings': { name: 'UK FCDO Warnings', enabled: true, priority: 2 },
  'dfat-warnings': { name: 'Australia DFAT Warnings', enabled: true, priority: 2 },
  'gac-warnings': { name: 'Canada GAC Warnings', enabled: true, priority: 2 },
  'gov-warning-convergence': { name: 'Multi-Gov Consensus Alert', enabled: true, priority: 1 },
  'dod-news': { name: 'Pentagon News', enabled: true, priority: 1 },
  'nato-news': { name: 'NATO Press', enabled: true, priority: 1 },
  'acaps-crises': { name: 'ACAPS Crisis Index', enabled: true, priority: 2 },
  'liveuamap': { name: 'Ukraine Frontline (LiveUA)', enabled: true, priority: 1 },
  'phishstats-feed': { name: 'PhishStats Threats', enabled: true, priority: 2 },
  'urlscan-threats': { name: 'URLScan Threat Feed', enabled: true, priority: 2 },
  'bitcoin-abuse': { name: 'Bitcoin Abuse Tracker', enabled: true, priority: 2 },
  'cve-tracker': { name: 'CVE Tracker', enabled: true, priority: 2 },
  'vulners-cve': { name: 'Vulners CVE Intel', enabled: true, priority: 2 },
  'mediastack-news': { name: 'MediaStack News', enabled: true, priority: 2 },
  'pulsedive-intel': { name: 'Pulsedive Threat Intel', enabled: true, priority: 2 },
  'hibp-breaches': { name: 'Breach Exposure', enabled: true, priority: 2 },
  'reddit-osint': { name: 'Reddit Signals', enabled: true, priority: 2 },
  'openaq-monitor': { name: 'OpenAQ Air Quality', enabled: true, priority: 2 },
  'ripe-ncc': { name: 'RIPE NCC BGP', enabled: true, priority: 2 },
  'ipinfo-lookup': { name: 'IPInfo Lookup', enabled: true, priority: 2 },
  'aerospace-reentry': { name: 'Aerospace Reentry Tracker', enabled: true, priority: 2 },
  'amtrak-alerts': { name: 'Amtrak Service Alerts', enabled: true, priority: 2 },
  'avalanche-hazard': { name: 'Avalanche Hazard', enabled: true, priority: 2 },
  'dsca-arms-transfers': { name: 'DSCA Arms Transfers', enabled: true, priority: 2 },
  'ecdc-surveillance': { name: 'ECDC Disease Surveillance', enabled: true, priority: 2 },
  'fdic-failures': { name: 'FDIC Bank Failures', enabled: true, priority: 2 },
  'habsos': { name: 'Harmful Algal Bloom Watch', enabled: true, priority: 2 },
  'un-security-council': { name: 'UN Security Council', enabled: true, priority: 1 },
  'wildfire-smoke': { name: 'Wildfire Smoke Tracker', enabled: true, priority: 2 },
  'central-bank-calendar': { name: 'Central Bank Calendar', enabled: true, priority: 2 },
  'congress-defense': { name: 'Congress Defense Activity', enabled: true, priority: 2 },
  'combatant-commands': { name: 'Combatant Commands', enabled: true, priority: 1 },
  'foreign-mil-news': { name: 'Foreign Military News', enabled: true, priority: 1 },
  'spc-mesoscale': { name: 'SPC Mesoscale Discussions', enabled: true, priority: 2 },
  'threat-intel-hub': { name: 'Threat Intel Hub', enabled: true, priority: 2 },
  'geo-intel': { name: 'Geo Intel', enabled: true, priority: 2 },
  'dark-web': { name: 'Dark Web', enabled: true, priority: 2 },
};

const FULL_MAP_LAYERS: MapLayers = {
  iranAttacks: true,
  gpsJamming: false,
  conflicts: true,
  bases: true,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: false,
  nuclear: true,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: true,
  waterways: true,
  outages: true,
  cyberThreats: true,
  datacenters: false,
  protests: false,
  flights: false,
  military: true,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: true,
  airstrikes: true,
  displacement: false,
  climate: false,
  // Tech layers (disabled in full variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled in full variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: true,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

const FULL_MOBILE_MAP_LAYERS: MapLayers = {
  iranAttacks: true,
  gpsJamming: false,
  conflicts: true,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: false,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled in full variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled in full variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

// ============================================
// TECH VARIANT (Tech/AI/Startups)
// ============================================
const TECH_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Global Tech Map', enabled: true, priority: 1 },
  insights: { name: 'AI Insights', enabled: true, priority: 1 },
  regulation: { name: 'AI Regulation Dashboard', enabled: true, priority: 1 },
  'tech-readiness': { name: 'Tech Readiness Index', enabled: true, priority: 1 },
  ai: { name: 'AI/ML News', enabled: true, priority: 1 },
  'tech-hubs': { name: 'Hot Tech Hubs', enabled: true, priority: 1 },
  tech: { name: 'Technology', enabled: true, priority: 1 },
  policy: { name: 'AI Policy & Regulation', enabled: true, priority: 1 },
  'live-news': { name: 'Tech Headlines', enabled: true, priority: 1 },
  'live-webcams': { name: 'Live Webcams', enabled: true, priority: 2 },
  startups: { name: 'Startups & VC', enabled: true, priority: 1 },
  vcblogs: { name: 'VC Insights & Essays', enabled: true, priority: 1 },
  regionalStartups: { name: 'Global Startup News', enabled: true, priority: 1 },
  unicorns: { name: 'Unicorn Tracker', enabled: true, priority: 1 },
  accelerators: { name: 'Accelerators & Demo Days', enabled: true, priority: 1 },
  security: { name: 'Cybersecurity', enabled: true, priority: 1 },
  layoffs: { name: 'Layoffs Tracker', enabled: true, priority: 1 },
  markets: { name: 'Tech Stocks', enabled: true, priority: 2 },
  finance: { name: 'Financial News', enabled: true, priority: 2 },
  crypto: { name: 'Crypto', enabled: true, priority: 2 },
  hardware: { name: 'Semiconductors & Hardware', enabled: true, priority: 2 },
  cloud: { name: 'Cloud & Infrastructure', enabled: true, priority: 2 },
  dev: { name: 'Developer Community', enabled: true, priority: 2 },
  github: { name: 'GitHub Trending', enabled: true, priority: 1 },
  ipo: { name: 'IPO & SPAC', enabled: true, priority: 2 },
  polymarket: { name: 'Tech Predictions', enabled: true, priority: 2 },
  funding: { name: 'Funding & VC', enabled: true, priority: 1 },
  producthunt: { name: 'Product Hunt', enabled: true, priority: 1 },
  events: { name: 'Tech Events', enabled: true, priority: 1 },
  'service-status': { name: 'Service Status', enabled: true, priority: 2 },
  economic: { name: 'Economic Indicators', enabled: true, priority: 2 },
  'macro-signals': { name: 'Market Radar', enabled: true, priority: 2 },
  'etf-flows': { name: 'BTC ETF Tracker', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 2 },
};

const TECH_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: true,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: true,
  economic: true,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: true,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  displacement: false,
  climate: false,
  // Tech layers (enabled in tech variant)
  startupHubs: true,
  cloudRegions: true,
  accelerators: false,
  techHQs: true,
  techEvents: true,
  // Finance layers (disabled in tech variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

const TECH_MOBILE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: true,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  displacement: false,
  climate: false,
  // Tech layers (limited on mobile)
  startupHubs: true,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: true,
  // Finance layers (disabled in tech variant)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

// ============================================
// FINANCE VARIANT (Markets/Trading)
// ============================================
const FINANCE_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Global Markets Map', enabled: true, priority: 1 },
  'live-news': { name: 'Market Headlines', enabled: true, priority: 1 },
  'live-webcams': { name: 'Live Webcams', enabled: true, priority: 2 },
  insights: { name: 'AI Market Insights', enabled: true, priority: 1 },
  markets: { name: 'Live Markets', enabled: true, priority: 1 },
  'markets-news': { name: 'Markets News', enabled: true, priority: 2 },
  forex: { name: 'Forex & Currencies', enabled: true, priority: 1 },
  bonds: { name: 'Fixed Income', enabled: true, priority: 1 },
  commodities: { name: 'Commodities & Futures', enabled: true, priority: 1 },
  'commodities-news': { name: 'Commodities News', enabled: true, priority: 2 },
  crypto: { name: 'Crypto & Digital Assets', enabled: true, priority: 1 },
  'crypto-news': { name: 'Crypto News', enabled: true, priority: 2 },
  centralbanks: { name: 'Central Bank Watch', enabled: true, priority: 1 },
  economic: { name: 'Economic Data', enabled: true, priority: 1 },
  'trade-policy': { name: 'Trade Policy', enabled: true, priority: 1 },
  'supply-chain': { name: 'Supply Chain', enabled: true, priority: 1 },
  'economic-news': { name: 'Economic News', enabled: true, priority: 2 },
  ipo: { name: 'IPOs, Earnings & M&A', enabled: true, priority: 1 },
  heatmap: { name: 'Sector Heatmap', enabled: true, priority: 1 },
  'macro-signals': { name: 'Market Radar', enabled: true, priority: 1 },
  derivatives: { name: 'Derivatives & Options', enabled: true, priority: 2 },
  fintech: { name: 'Fintech & Trading Tech', enabled: true, priority: 2 },
  regulation: { name: 'Financial Regulation', enabled: true, priority: 2 },
  institutional: { name: 'Hedge Funds & PE', enabled: true, priority: 2 },
  analysis: { name: 'Market Analysis', enabled: true, priority: 2 },
  'etf-flows': { name: 'BTC ETF Tracker', enabled: true, priority: 2 },
  stablecoins: { name: 'Stablecoins', enabled: true, priority: 2 },
  'gcc-investments': { name: 'GCC Investments', enabled: true, priority: 2 },
  gccNews: { name: 'GCC Business News', enabled: true, priority: 2 },
  polymarket: { name: 'Predictions', enabled: true, priority: 2 },
  monitors: { name: 'My Monitors', enabled: true, priority: 2 },
};

const FINANCE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: true,
  pipelines: true,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: true,
  weather: true,
  economic: true,
  waterways: true,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled in finance variant)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (enabled in finance variant)
  stockExchanges: true,
  financialCenters: true,
  centralBanks: true,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: true,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

const FINANCE_MOBILE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: true,
  waterways: false,
  outages: true,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (limited on mobile)
  stockExchanges: true,
  financialCenters: false,
  centralBanks: true,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

// ============================================
// HAPPY VARIANT (Good News & Progress)
// ============================================
const HAPPY_PANELS: Record<string, PanelConfig> = {
  map: { name: 'World Map', enabled: true, priority: 1 },
  'positive-feed': { name: 'Good News Feed', enabled: true, priority: 1 },
  progress: { name: 'Human Progress', enabled: true, priority: 1 },
  counters: { name: 'Live Counters', enabled: true, priority: 1 },
  spotlight: { name: "Today's Hero", enabled: true, priority: 1 },
  breakthroughs: { name: 'Breakthroughs', enabled: true, priority: 1 },
  digest: { name: '5 Good Things', enabled: true, priority: 1 },
  species: { name: 'Conservation Wins', enabled: true, priority: 1 },
  renewable: { name: 'Renewable Energy', enabled: true, priority: 1 },
  giving: { name: 'Global Giving', enabled: true, priority: 1 },
};

const HAPPY_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: false,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: true,
  kindness: true,
  happiness: true,
  speciesRecovery: true,
  renewableInstallations: true,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

const HAPPY_MOBILE_MAP_LAYERS: MapLayers = {
  gpsJamming: false,
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: false,
  ais: false,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: false,
  economic: false,
  waterways: false,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: false,
  military: false,
  natural: false,
  spaceports: false,
  minerals: false,
  fires: false,
  // Data source layers
  ucdpEvents: false,
  airstrikes: false,
  displacement: false,
  climate: false,
  // Tech layers (disabled)
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  // Finance layers (disabled)
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  // Happy variant layers
  positiveEvents: true,
  kindness: true,
  happiness: true,
  speciesRecovery: true,
  renewableInstallations: true,
  tradeRoutes: false,
  iranAttacks: false,
  s2pimu: false,
  dayNight: false,
  faaWeatherCams: false,
  adsb: false,
  acledEvents: false,
  militaryFlights: false,
  diseaseIntel: false,
};

// ============================================
// VARIANT-AWARE EXPORTS
// ============================================
export const DEFAULT_PANELS = SITE_VARIANT === 'happy' ? HAPPY_PANELS : SITE_VARIANT === 'tech' ? TECH_PANELS : SITE_VARIANT === 'finance' ? FINANCE_PANELS : FULL_PANELS;
export const DEFAULT_MAP_LAYERS = SITE_VARIANT === 'happy' ? HAPPY_MAP_LAYERS : SITE_VARIANT === 'tech' ? TECH_MAP_LAYERS : SITE_VARIANT === 'finance' ? FINANCE_MAP_LAYERS : FULL_MAP_LAYERS;
export const MOBILE_DEFAULT_MAP_LAYERS = SITE_VARIANT === 'happy' ? HAPPY_MOBILE_MAP_LAYERS : SITE_VARIANT === 'tech' ? TECH_MOBILE_MAP_LAYERS : SITE_VARIANT === 'finance' ? FINANCE_MOBILE_MAP_LAYERS : FULL_MOBILE_MAP_LAYERS;

/** Maps map-layer toggle keys to their data-freshness source IDs (single source of truth). */
export const LAYER_TO_SOURCE: Partial<Record<keyof MapLayers, DataSourceId[]>> = {
  military: ['opensky', 'wingbits'],
  ais: ['ais'],
  natural: ['usgs'],
  weather: ['weather'],
  outages: ['outages'],
  cyberThreats: ['cyber_threats'],
  protests: ['acled', 'gdelt_doc'],
  ucdpEvents: ['ucdp_events'],
  displacement: ['unhcr'],
  climate: ['climate'],
  faaWeatherCams: ['faa_weather_cams'],
  adsb: ['adsb'],
  acledEvents: ['acled'],
  militaryFlights: ['adsb-military'],
};

// ============================================
// PANEL CATEGORY MAP (variant-aware)
// ============================================
// Maps category keys to panel keys. Only categories with at least one
// matching panel in the active variant's DEFAULT_PANELS are shown.
// The `variants` field restricts a category to specific site variants;
// omit it to show the category for all variants.
export const PANEL_CATEGORY_MAP: Record<string, { labelKey: string; panelKeys: string[]; variants?: string[] }> = {
  // All variants — essential panels
  core: {
    labelKey: 'header.panelCatCore',
    panelKeys: ['map', 'insights', 'strategic-posture', 'live-news', 'live-webcams'],
  },

  // Full (geopolitical) variant
  intelligence: {
    labelKey: 'header.panelCatIntelligence',
    panelKeys: ['watchlist', 'saved-places', 'watchlist-locations', 'local-logistics', 'comms-plan', 'unified-alert-inbox', 'alert-rules', 'situation-awareness', 'alert-center', 'strategic-risk', 'cii', 'geo-hubs', 'intel', 'gdelt-intel', 'cascade', 'telegram-intel'],
    variants: ['full'],
  },
  regionalNews: {
    labelKey: 'header.panelCatRegionalNews',
    panelKeys: ['politics', 'us', 'europe', 'middleeast', 'africa', 'latam', 'asia'],
    variants: ['full'],
  },
  marketsFinance: {
    labelKey: 'header.panelCatMarketsFinance',
    panelKeys: ['commodities', 'markets', 'economic', 'economic-stress', 'federal-register', 'trade-policy', 'supply-chain', 'finance', 'polymarket', 'macro-signals', 'etf-flows', 'stablecoins', 'crypto', 'heatmap', 'fear-greed', 'national-debt', 'fuel-prices'],
    variants: ['full'],
  },
  topical: {
    labelKey: 'header.panelCatTopical',
    panelKeys: ['energy', 'gov', 'thinktanks', 'tech', 'ai', 'layoffs'],
    variants: ['full'],
  },
  dataTracking: {
    labelKey: 'header.panelCatDataTracking',
    panelKeys: ['monitors', 'cyber-threats', 'local-ids', 'comms-health', 'ucdp-events', 'nuclear-risk', 'airstrikes', 'displacement', 'security-advisories', 'oref-sirens', 'space-weather', 'spaceflight-news', 'space-launches', 'population-exposure', 'internet-disruptions', 'air-traffic', 'threat-intel-hub', 'geo-intel', 'dark-web'],
    variants: ['full'],
  },
  hazards: {
    labelKey: 'header.panelCatHazards',

    panelKeys: ['satellite-fires', 'earthquakes', 'gdacs-alerts', 'volcano-alerts', 'nws-alerts', 'faa-weather-cams', 'tsunami-alerts', 'tropical-cyclones', 'climate', 'wildfire-incidents', 'hazmat-incidents', 'oil-spill'],
    variants: ['full'],
  },
  healthEnv: {
    labelKey: 'header.panelCatHealthEnv',
    panelKeys: ['hazard-alerts', 'infrastructure', 'giving', 'daily-wisdom', 'stoic-reflections', 'biblical-encouragement', 'alan-watts-reflections', 'mckenna-visions', 'disease-outbreaks', 'disease-intel', 'humanitarian-crisis', 'air-quality', 'food-insecurity', 'radiation-decay', 'resource-inventory'],
    variants: ['full'],
  },

  // Tech variant
  techAi: {
    labelKey: 'header.panelCatTechAi',
    panelKeys: ['tech-readiness', 'ai', 'tech-hubs', 'tech', 'hardware', 'cloud', 'dev', 'github', 'producthunt', 'events', 'service-status'],
    variants: ['tech'],
  },
  startupsVc: {
    labelKey: 'header.panelCatStartupsVc',
    panelKeys: ['startups', 'vcblogs', 'regionalStartups', 'unicorns', 'accelerators', 'funding', 'ipo'],
    variants: ['tech'],
  },
  securityPolicy: {
    labelKey: 'header.panelCatSecurityPolicy',
    panelKeys: ['regulation', 'policy', 'security'],
    variants: ['tech'],
  },
  techMarkets: {
    labelKey: 'header.panelCatMarkets',
    panelKeys: ['markets', 'finance', 'crypto', 'economic', 'polymarket', 'macro-signals', 'etf-flows', 'stablecoins', 'layoffs', 'monitors'],
    variants: ['tech'],
  },

  // Finance variant
  finMarkets: {
    labelKey: 'header.panelCatMarkets',
    panelKeys: ['markets', 'markets-news', 'heatmap', 'macro-signals', 'analysis', 'polymarket'],
    variants: ['finance'],
  },
  fixedIncomeFx: {
    labelKey: 'header.panelCatFixedIncomeFx',
    panelKeys: ['forex', 'bonds'],
    variants: ['finance'],
  },
  finCommodities: {
    labelKey: 'header.panelCatCommodities',
    panelKeys: ['commodities', 'commodities-news'],
    variants: ['finance'],
  },
  cryptoDigital: {
    labelKey: 'header.panelCatCryptoDigital',
    panelKeys: ['crypto', 'crypto-news', 'etf-flows', 'stablecoins', 'fintech'],
    variants: ['finance'],
  },
  centralBanksEcon: {
    labelKey: 'header.panelCatCentralBanks',
    panelKeys: ['centralbanks', 'economic', 'trade-policy', 'supply-chain', 'economic-news'],
    variants: ['finance'],
  },
  dealsInstitutional: {
    labelKey: 'header.panelCatDeals',
    panelKeys: ['ipo', 'derivatives', 'institutional', 'regulation'],
    variants: ['finance'],
  },
  gulfMena: {
    labelKey: 'header.panelCatGulfMena',
    panelKeys: ['gcc-investments', 'gccNews', 'monitors'],
    variants: ['finance'],
  },
};

// Monitor palette — fixed category colors persisted to localStorage (not theme-dependent)
export const MONITOR_COLORS = [
  '#44ff88',
  '#ff8844',
  '#4488ff',
  '#ff44ff',
  '#ffff44',
  '#ff4444',
  '#44ffff',
  '#88ff44',
  '#ff88ff',
  '#88ffff',
];

export const STORAGE_KEYS = {
  panels: 'worldmonitor-panels',
  monitors: 'worldmonitor-monitors',
  mapLayers: 'worldmonitor-layers',
  disabledFeeds: 'worldmonitor-disabled-feeds',
} as const;
